# Generated by Django 3.0.7 on 2020-06-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_scene_name', models.CharField(max_length=200)),
                ('m_text_index', models.IntegerField(default=0)),
                ('m_active_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='KeyTable',
        ),
    ]
